name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  start-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Welcome on GitHub Actions"
  checkout-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
  
  install-dependencies:
    needs: checkout-repository
    runs-on: ubuntu-latest
    steps:
      - run: echo "Installing dependencies ..."
